##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by dev-cetera.com & contributors. The use of this
## source code is governed by an MIT-style license described in the LICENSE
## file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_bijective_uuid_mapper
description: A package providing bijective UUID mapping for secure and efficienct lookups.
version: 0.1.4
repository: https://github.com/dev-cetera/df_bijective_uuid_mapper
funding:
  - https://www.buymeacoffee.com/dev_cetera
topics:
  - uuid
  - security
  - cryptography
  - cloud-functions
  - utility

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.0.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  crypto: ^3.0.5

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^5.0.0
